core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
]

inventory/urls.py
from django.urls import path
from . import views


app_name = 'inventory'
urlpatterns = [
    path('items/', views.ItemListView.as_view(), name='item-list'),
    path('items/create/', views.ItemCreateView.as_view(), name='item-create'),
    path('items/<int:pk>/', views.ItemDetailView.as_view(), name='item-detail'),
    path('items/<int:pk>/update/', views.ItemUpdateView.as_view(), name='item-update'),
    path('items/<int:pk>/delete/', views.ItemDeleteView.as_view(), name='item-delete'),
    path('units/', views.UnitListView.as_view(), name='unit-list'),
    path('units/create/', views.UnitCreateView.as_view(), name='unit-create'),
    path('units/<int:pk>/update/', views.UnitUpdateView.as_view(), name='unit-update'),
    path('units/<int:pk>/delete/', views.UnitDeleteView.as_view(), name='unit-delete'),
]

orders/urls.py
from django.urls import path

urlpatterns = [
    
]

pos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('inventory/', include('inventory.urls')),
]

core/models.py
from django.db import models

# Create your models here.

inventory/models.py
from django.db import models

# Create your models here.


class Unit(models.Model):
    name = models.CharField(max_length=30)
    abbreviation = models.CharField(max_length=5)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Item(models.Model):
    code = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from inventory.models import Item
# Create your models here.

STATUS_CHOICES = (
    (0, 'Pendiente'),
    (1, 'Pagado'),
)


class Order(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    created_at = models.DateTimeField(auto_now_add=True)


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)

inventory/forms.py
from django.forms import ModelForm, TextInput, Textarea
from .models import Item


class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        widgets = {
            'description': Textarea(attrs={'class': 'textarea', 'rows': '2'})
        }

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from inventory.models import Item
# Create your views here.


class DashboardView(TemplateView):
    template_name = 'core/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['items'] = Item.objects.count()
        return context

inventory/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Item, Unit
from .forms import ItemForm

# Create your views here.

# Unit Views


class UnitListView(ListView):
    model = Unit


class UnitCreateView(CreateView):
    model = Unit
    fields = '__all__'
    success_url = reverse_lazy('inventory:unit-list')


class UnitUpdateView(UpdateView):
    model = Unit
    fields = '__all__'
    template_name = 'inventory/unit_edit_form.html'
    success_url = reverse_lazy('inventory:unit-list')


class UnitDeleteView(DeleteView):
    model = Unit
    success_url = reverse_lazy('inventory:unit-list')

# Item Views


class ItemListView(ListView):
    model = Item


class ItemDetailView(DetailView):
    model = Item


class ItemCreateView(CreateView):
    form_class = ItemForm
    template_name = 'inventory/item_form.html'
    success_url = reverse_lazy('inventory:item-list')


class ItemUpdateView(UpdateView):
    model = Item
    template_name = 'inventory/item_edit_form.html'
    form_class = ItemForm
    success_url = reverse_lazy('inventory:item-list')


class ItemDeleteView(DeleteView):
    model = Item
    success_url = reverse_lazy('inventory:item-list')

orders/views.py
from django.shortcuts import render

# Create your views here.

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %} NopalPOS</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'core/css/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/fa/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/main.css' %}">
    {% block styles %}{% endblock %}
</head>

<body>
    <div class="layout">
        {% include 'core/navbar.html' %}
        <div class="layout-body">
            <div class="layout-nav">
                {% include 'core/sidebar.html' %}
            </div>
            <div class="layout-content">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    {% block scripts %}{% endblock %}
</body>

</html>

core/templates/core/dashboard.html
{% extends 'core/base.html' %}

{% block content %}

<div class="columns is-multiline">
    <div class="column is-12-tablet is-6-desktop is-3-widescreen">
        <div class="notification is-info">
            <p class="title is-1">
                {{ items }}
            </p>
            <p class="subtitle is-4">
                Productos
            </p>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>document.querySelector('#dashboard-link').classList.add('is-active');</script>
{% endblock %}

core/templates/core/navbar.html
<nav class="navbar is-black" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'core:dashboard' %}">
            NopalPOS
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbar" class="navbar-menu">

        <div class="navbar-end">

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    Usuario
                </a>

                <div class="navbar-dropdown is-right">
                    <a class="navbar-item">
                        Perfil
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item">
                        Cerrar Sesión
                    </a>
                </div>
            </div>
        </div>
    </div>
</nav>

core/templates/core/sidebar.html
<div class="sidebar">
  <a id="dashboard-link" href="{% url 'core:dashboard' %}" class="sidebar-link">
    <span class="icon has-text-black is-medium">
      <i class="fas fa-tachometer-alt fa-fw fa-2x"></i>
    </span>
    <span class="text">
      Tablero
    </span>
  </a>
  <a id="items-link" href="{% url 'inventory:item-list' %}" class="sidebar-link">
    <span class="icon has-text-black is-medium">
      <i class="fas fa-box fa-fw fa-2x"></i>
    </span>
    <span class="text">
      Productos
    </span>
  </a>
  <a id="units-link" href="{% url 'inventory:unit-list' %}" class="sidebar-link">
    <span class="icon has-text-black is-medium">
      <i class="fas fa-balance-scale fa-fw fa-2x"></i>
    </span>
    <span class="text">
      Unidades
    </span>
  </a>
</div>

inventory/templates/inventory/item_confirm_delete.html
{% extends 'core/base.html' %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title">¿Estás seguro que deseas eliminar este producto?</h1>
        <h2 class="subtitle">&nbsp; Detalles:  {{ object.name }}</h2>
        <br>
        <form action="{% url 'inventory:item-delete' object.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="button is-danger is-medium">
                <span class="icon"><i class="fas fa-trash"></i></span>
                <span>Eliminar</span>
            </button>
            <a href="{% url 'inventory:item-list' %}" class="button is-light is-medium">
                <span class="icon"><i class="fas fa-times-circle"></i></span>
                <span>Cancelar</span>
            </a>
        </form>
    </div>
</section>
{% endblock %}

{% block scripts %}
<script>
    document.querySelector('#items-link').classList.add('is-active'); 
</script>
{% endblock %}

inventory/templates/inventory/item_detail.html
{% extends 'core/base.html' %}

{% block content %}
<section class="section">
    <div class="container">
        <nav class="breadcrumb is-medium" aria-label="breadcrumbs">
            <ul>
                <li><a href="{% url 'inventory:item-list' %}">Productos</a></li>
                <li class="is-active"><a href="{% url 'inventory:item-detail' object.id %}">{{ object.name }}</a></li>
            </ul>
        </nav>
        <h1 class="title">Detalles de producto</h1>
        <div class="content is-large">
            <p>
                <b>ID:</b> {{ object.id }}
            </p>
            <p>
                <b>Código:</b> {{ object.code }}
            </p>
            <p>
                <b>Nombre:</b> {{ object.name }}
            </p>
            {% if object.description %}
            <p>
                <b>Descripción:</b> 
                <br>
                {{ object.description }}
            </p>
            {% endif %}
            <p>
                <b>Precio:</b> $ {{ object.price }}
            </p>
            <p>
                <b>Costo:</b> $ {{ object.cost }}
            </p>
            <p>
                <b>Unidad:</b> {{ object.unit }}
            </p>
            <p>
                <b>Cantidad:</b> {{ object.quantity }} {{ object.unit.abbreviation }}
            </p>
            <p>
                <b>Fecha de creación:</b> {{ object.created_at }}
            </p>
            <p>
                <b>Fecha de modificación:</b> {{ object.updated_at }}
            </p>
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
<script>
    document.querySelector('#items-link').classList.add('is-active');
</script>
{% endblock %}

inventory/templates/inventory/item_edit_form.html
{% extends 'core/base.html' %}

{% block content %}
{% load extras %}
<section class="section">
    <div class="container">
        <nav class="breadcrumb is-medium" aria-label="breadcrumbs">
            <ul>
                <li><a href="{% url 'inventory:item-list' %}">Productos</a></li>
                <li><a href="{% url 'inventory:item-detail' object.id %}">{{ object.name }}</a></li>
                <li class="is-active"><a href="{% url 'inventory:item-update' object.id %}">Editar</a></li>
            </ul>
        </nav>
        <h1 class="title">Editar producto</h1>

        <form action="{% url 'inventory:item-update' object.id %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="columns">

                <div class="column">
                    <div class="field">
                        <label for="{{ form.code.id_for_label }}" class="label">Código:</label>
                        <div class="control">
                            {% if form.code.errors %}
                            {{ form.code|addcss:"input is-danger" }}
                            {% else %}
                            {{ form.code|addcss:"input" }}
                            {% endif %}
                        </div>
                        {% if form.code.errors %}
                        {% for error in form.code.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <div class="column">
                    <div class="field">
                        <label for="{{ form.name.id_for_label }}" class="label">Nombre:</label>
                        <div class="control">
                            {% if form.name.errors %}
                            {{ form.name|addcss:"input is-danger" }}
                            {% else %}
                            {{ form.name|addcss:"input" }}
                            {% endif %}
                        </div>
                        {% if form.name.errors %}
                        {% for error in form.name.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="field">
                <label for="{{ form.description.id_for_label }}" class="label">Descripción:</label>
                <div class="control">
                    {% if form.description.errors %}
                    {{ form.description|addcss:"is-danger" }}
                    {% else %}
                    {{ form.description }}
                    {% endif %}
                </div>
                {% if form.description.errors %}
                {% for error in form.description.errors %}
                <p class="help is-danger">
                    {{ error|escape }}
                </p>
                {% endfor %}
                {% endif %}
            </div>
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <label for="{{ form.unit.id_for_label }}" class="label">Unidad:</label>
                        <div class="control">
                            <div class="select is-fullwidth">
                                {% if form.unit.errors %}
                                {{ form.unit|addcss:"is-danger" }}
                                {% else %}
                                {{ form.unit }}
                                {% endif %}
                            </div>
                        </div>
                        {% if form.unit.errors %}
                        {% for error in form.unit.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>

                </div>
                <div class="column">
                    <div class="field">
                        <label for="{{ form.quantity.id_for_label }}" class="label">Cantidad:</label>
                        <div class="control">
                            {% if form.quantity.errors %}
                            {{ form.quantity|addcss:"input is-danger" }}
                            {% else %}
                            {{ form.quantity|addcss:"input" }}
                            {% endif %}
                        </div>
                        {% if form.quantity.errors %}
                        {% for error in form.quantity.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="columns">

                <div class="column">
                    <div class="field">
                        <label for="{{ form.price.id_for_label }}" class="label">Precio por unidad:</label>
                        <div class="control">
                            {% if form.price.errors %}
                            {{ form.price|addcss:"input is-danger" }}
                            {% else %}
                            {{ form.price|addcss:"input" }}
                            {% endif %}
                        </div>
                        {% if form.price.errors %}
                        {% for error in form.price.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="column">

                    <div class="field">
                        <label for="{{ form.cost.id_for_label }}" class="label">Costo por unidad:</label>
                        <div class="control">
                            {% if form.cost.errors %}
                            {{ form.cost|addcss:"input is-danger" }}
                            {% else %}
                            {{ form.cost|addcss:"input" }}
                            {% endif %}
                        </div>
                        {% if form.cost.errors %}
                        {% for error in form.cost.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>



            <div class="field">
                <button type="submit" class="button is-link is-medium">
                    <span class="icon"><i class="fas fa-save"></i></span>
                    <span>Guardar</span>
                </button>
                <button type="reset" class="button is-light is-medium">
                    <span class="icon"><i class="fas fa-times-circle"></i></span>
                    <span>Cancelar</span>
                </button>
            </div>
        </form>

    </div>
</section>
{% endblock %}


{% block scripts %}
<script>
    document.querySelector('#items-link').classList.add('is-active');
</script>
{% endblock %}

inventory/templates/inventory/item_form.html
{% extends 'core/base.html' %}

{% block content %}
{% load extras %}
<section class="section">
    <div class="container">
        <nav class="breadcrumb is-medium" aria-label="breadcrumbs">
            <ul>
                <li><a href="{% url 'inventory:item-list' %}">Productos</a></li>
                <li class="is-active"><a href="{% url 'inventory:item-create' %}">Nuevo</a></li>
            </ul>
        </nav>
        <h1 class="title">Nuevo producto</h1>

        <form action="{% url 'inventory:item-create' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="columns">

                <div class="column">
                    <div class="field">
                        <label for="{{ form.code.id_for_label }}" class="label">Código:</label>
                        <div class="control">
                            {% if form.code.errors %}
                            {{ form.code|addcss:"input is-danger" }}
                            {% else %}
                            {{ form.code|addcss:"input" }}
                            {% endif %}
                        </div>
                        {% if form.code.errors %}
                        {% for error in form.code.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <div class="column">
                    <div class="field">
                        <label for="{{ form.name.id_for_label }}" class="label">Nombre:</label>
                        <div class="control">
                            {% if form.name.errors %}
                            {{ form.name|addcss:"input is-danger" }}
                            {% else %}
                            {{ form.name|addcss:"input" }}
                            {% endif %}
                        </div>
                        {% if form.name.errors %}
                        {% for error in form.name.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="field">
                <label for="{{ form.description.id_for_label }}" class="label">Descripción:</label>
                <div class="control">
                    {% if form.description.errors %}
                    {{ form.description|addcss:"is-danger" }}
                    {% else %}
                    {{ form.description }}
                    {% endif %}
                </div>
                {% if form.description.errors %}
                {% for error in form.description.errors %}
                <p class="help is-danger">
                    {{ error|escape }}
                </p>
                {% endfor %}
                {% endif %}
            </div>
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <label for="{{ form.unit.id_for_label }}" class="label">Unidad:</label>
                        <div class="control">
                            <div class="select is-fullwidth">
                                {% if form.unit.errors %}
                                {{ form.unit|addcss:"is-danger" }}
                                {% else %}
                                {{ form.unit }}
                                {% endif %}
                            </div>
                        </div>
                        {% if form.unit.errors %}
                        {% for error in form.unit.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>

                </div>
                <div class="column">
                    <div class="field">
                        <label for="{{ form.quantity.id_for_label }}" class="label">Cantidad:</label>
                        <div class="control">
                            {% if form.quantity.errors %}
                            {{ form.quantity|addcss:"input is-danger" }}
                            {% else %}
                            {{ form.quantity|addcss:"input" }}
                            {% endif %}
                        </div>
                        {% if form.quantity.errors %}
                        {% for error in form.quantity.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="columns">

                <div class="column">
                    <div class="field">
                        <label for="{{ form.price.id_for_label }}" class="label">Precio por unidad:</label>
                        <div class="control">
                            {% if form.price.errors %}
                            {{ form.price|addcss:"input is-danger" }}
                            {% else %}
                            {{ form.price|addcss:"input" }}
                            {% endif %}
                        </div>
                        {% if form.price.errors %}
                        {% for error in form.price.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="column">

                    <div class="field">
                        <label for="{{ form.cost.id_for_label }}" class="label">Costo por unidad:</label>
                        <div class="control">
                            {% if form.cost.errors %}
                            {{ form.cost|addcss:"input is-danger" }}
                            {% else %}
                            {{ form.cost|addcss:"input" }}
                            {% endif %}
                        </div>
                        {% if form.cost.errors %}
                        {% for error in form.cost.errors %}
                        <p class="help is-danger">
                            {{ error|escape }}
                        </p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>



            <div class="field">
                <button type="submit" class="button is-link is-medium">
                    <span class="icon"><i class="fas fa-save"></i></span>
                    <span>Guardar</span>
                </button>
                <button type="reset" class="button is-light is-medium">
                    <span class="icon"><i class="fas fa-times-circle"></i></span>
                    <span>Cancelar</span>
                </button>
            </div>
        </form>

    </div>
</section>
{% endblock %}


{% block scripts %}
<script>
    document.querySelector('#items-link').classList.add('is-active');
</script>
{% endblock %}

inventory/templates/inventory/item_list.html
{% extends 'core/base.html' %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title">Productos</h1>
        <a href="{% url 'inventory:item-create' %}" class="button is-success">
            <span class="icon"><i class="fas fa-plus"></i></span>
            <span>Añadir nuevo</span>
        </a>
        <br>
        <br>
        <div class="table-container">
            <table class="table is-striped is-fullwidth">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Cantidad</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                    <tr>
                        <td>{{ item.code }}</td>
                        <td><a href="{% url 'inventory:item-detail' item.id %}">{{ item.name }}</a></td>
                        <td>${{ item.price }}</td>
                        <td>{{ item.quantity}} {{ item.unit.name }}</td>
                        <td>
                            <a href="{% url 'inventory:item-update' item.id %}" class="button is-info"><span class="icon"><i class="fas fa-edit"></i></span></a>
                            <a href="{% url 'inventory:item-delete' item.id %}" class="button is-danger"><span class="icon"><i class="fas fa-trash"></i></span></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
<script>
document.querySelector('#items-link').classList.add('is-active');
</script>
{% endblock %}

inventory/templates/inventory/unit_confirm_delete.html
{% extends 'core/base.html' %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title">¿Estás seguro que deseas eliminar esta unidad?</h1>
        <h2 class="subtitle">&nbsp; Detalles:  {{ object.name }}</h2>
        <br>
        <form action="{% url 'inventory:unit-delete' object.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="button is-danger is-medium">
                <span class="icon"><i class="fas fa-trash"></i></span>
                <span>Eliminar</span>
            </button>
            <a href="{% url 'inventory:item-list' %}" class="button is-light is-medium">
                <span class="icon"><i class="fas fa-times-circle"></i></span>
                <span>Cancelar</span>
            </a>
        </form>
    </div>
</section>
{% endblock %}

{% block scripts %}
<script>
    document.querySelector('#units-link').classList.add('is-active'); 
</script>
{% endblock %}

inventory/templates/inventory/unit_list.html
{% extends 'core/base.html' %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title">Unidades</h1>
        <a href="{% url 'inventory:unit-create' %}" class="button is-success">
            <span class="icon"><i class="fas fa-plus"></i></span>
            <span>Añadir nueva</span>
        </a>
        <br>
        <br>
        <div class="table-container">
            <table class="table is-striped is-fullwidth">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for unit in object_list %}
                    <tr>
                        <td>{{ unit.name }}</td>
                        <td>
                            <a href="{% url 'inventory:unit-update' unit.id %}" class="button is-info"><span class="icon"><i class="fas fa-edit"></i></span></a>
                            <a href="{% url 'inventory:unit-delete' unit.id %}" class="button is-danger"><span class="icon"><i class="fas fa-trash"></i></span></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
<script>
document.querySelector('#units-link').classList.add('is-active');
</script>
{% endblock %}